[package]
name = "counter-client"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = { version = "1.5.0", features = ["derive"] }
solana-sdk = "1.18.14"
solana-client = "1.18.14"
solana-program = "1.18.14"
clap = { version = "4.5.4", features = ["derive"] }


